"""EQUIPA initiative plan file helpers (Phase 1).

An *initiative* is a long-horizon piece of work composed of multiple
dispatched tasks. Phase 1 introduces shared working memory across those
tasks via a per-initiative plan file at::

    <target-repo>/.equipa/initiative-<id>.md

The orchestrator is the SINGLE WRITER to the plan file. Agents read it
(as they read any other repo file) but never write to it; they emit a
structured ``ORCHESTRATOR_OUTPUT`` block which the orchestrator parses
and appends to the plan.

Key invariants:

* Everything ABOVE the ``<!-- BEGIN ORCHESTRATOR-MANAGED -->`` marker is
  human-editable; the orchestrator never touches it.
* Everything BETWEEN the BEGIN and END markers is orchestrator-exclusive
  and append-only (newest sub-task at the bottom).
* Writes are atomic: ``tempfile + os.rename``. The plan file is never
  left in a half-written state, even on crash.
* A file-level lock (``fcntl.flock`` on POSIX) serialises parallel
  appends from concurrent task dispatches in the same initiative.
  Windows callers must serialise externally — see :func:`_acquire_lock`.

Public surface::

    InitiativePlan.load(repo_path, initiative_id) -> InitiativePlan
    InitiativePlan.ensure_exists(repo_path, initiative_id, conn) -> Path
    plan.append_subtask(task_id, title, status, branch, completed_at,
                        summary, decisions) -> None
    plan.to_prompt_context() -> str

    parse_orchestrator_output(raw_text) -> ParsedOutput | None

Copyright 2026 Forgeborn
"""

from __future__ import annotations

import contextlib
import logging
import os
import re
import sqlite3
import tempfile
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Iterable, Iterator

logger = logging.getLogger(__name__)


BEGIN_MARKER = "<!-- BEGIN ORCHESTRATOR-MANAGED -->"
END_MARKER = "<!-- END ORCHESTRATOR-MANAGED -->"
HUMAN_EDIT_HINT = (
    "<!-- AUTO-MAINTAINED BY ORCHESTRATOR BELOW THIS LINE — do not edit by hand -->"
)

PROMPT_HEADER = (
    "You are working in a long-horizon EQUIPA initiative. The plan below "
    "is shared working memory across every task in this initiative — read "
    "it, build on prior decisions, and avoid re-treading dead-ends already "
    "recorded as failed approaches. Do NOT edit this file directly; the "
    "orchestrator will append your structured output after you finish."
)


# ---------------------------------------------------------------------------
# Parsing
# ---------------------------------------------------------------------------

ORCHESTRATOR_OUTPUT_RE = re.compile(
    r"<!--\s*ORCHESTRATOR_OUTPUT\s*-->(.*?)<!--\s*/ORCHESTRATOR_OUTPUT\s*-->",
    re.DOTALL,
)


@dataclass
class ParsedOutput:
    """Parsed result of an agent's ``ORCHESTRATOR_OUTPUT`` block."""

    summary: str = ""
    decisions: list[tuple[str, str]] = field(default_factory=list)
    malformed: bool = False


def parse_orchestrator_output(raw_text: str) -> ParsedOutput | None:
    """Parse the agent's final ``ORCHESTRATOR_OUTPUT`` block.

    Returns ``None`` if the block is absent (callers should log a warning
    and append a placeholder entry). If multiple blocks are present, the
    LAST one wins — agents may emit revised drafts.

    Tolerates: missing pipe separator (whole line is treated as the
    decision text, rationale empty), extra whitespace, missing or empty
    ``DECISIONS:`` section.
    """
    if not raw_text:
        return None

    matches = ORCHESTRATOR_OUTPUT_RE.findall(raw_text)
    if not matches:
        return None

    body = matches[-1]
    result = ParsedOutput()

    # Split into SUMMARY and DECISIONS sections by scanning line-by-line.
    summary_lines: list[str] = []
    decision_lines: list[str] = []
    section: str | None = None
    for raw_line in body.splitlines():
        line = raw_line.rstrip()
        stripped = line.strip()
        if not stripped:
            if section == "summary":
                summary_lines.append("")
            continue
        if stripped.upper().startswith("SUMMARY:"):
            section = "summary"
            after = stripped.split(":", 1)[1].strip()
            if after:
                summary_lines.append(after)
            continue
        if stripped.upper().startswith("DECISIONS:"):
            section = "decisions"
            after = stripped.split(":", 1)[1].strip()
            if after:
                decision_lines.append(after)
            continue
        if section == "summary":
            summary_lines.append(stripped)
        elif section == "decisions":
            decision_lines.append(stripped)

    result.summary = " ".join(s for s in summary_lines if s).strip()

    for entry in decision_lines:
        # Bullet markers are optional; strip them.
        entry = entry.lstrip("-*•").strip()
        if not entry:
            continue
        if "|" in entry:
            decision, rationale = entry.split("|", 1)
            result.decisions.append((decision.strip(), rationale.strip()))
        else:
            # Tolerate missing separator.
            result.decisions.append((entry, ""))
            result.malformed = True

    if not result.summary:
        result.malformed = True

    return result


# ---------------------------------------------------------------------------
# File lock helpers
# ---------------------------------------------------------------------------

@contextlib.contextmanager
def _acquire_lock(lock_path: Path) -> Iterator[None]:
    """Exclusive file lock for serialising plan-file writes.

    POSIX implementation uses ``fcntl.flock``. The lock is released
    automatically when the context exits (including on exception).

    On Windows ``fcntl`` is unavailable; callers there must serialise
    externally (e.g. a process-wide threading.Lock keyed on the path).
    This module intentionally does NOT silently no-op the lock on
    Windows — a corruption-prone fallback is worse than a clear error
    at import time when someone tries to run EQUIPA orchestrator on a
    platform we have not validated.
    """
    try:
        import fcntl  # POSIX-only
    except ImportError as exc:  # pragma: no cover - non-POSIX platform
        raise RuntimeError(
            "Plan-file locking requires fcntl (POSIX). On Windows, "
            "serialise InitiativePlan.append_subtask calls externally."
        ) from exc

    lock_path.parent.mkdir(parents=True, exist_ok=True)
    fd = os.open(str(lock_path), os.O_RDWR | os.O_CREAT, 0o644)
    try:
        fcntl.flock(fd, fcntl.LOCK_EX)
        yield
    finally:
        try:
            fcntl.flock(fd, fcntl.LOCK_UN)
        finally:
            os.close(fd)


# ---------------------------------------------------------------------------
# Plan structure
# ---------------------------------------------------------------------------

@dataclass
class InitiativeRow:
    """In-memory view of an initiatives DB row used to render the header."""

    id: int
    project_id: int
    name: str
    goal: str
    status: str
    created_at: str
    project_codename: str | None = None


@dataclass
class InitiativePlan:
    """Loaded representation of an initiative plan file."""

    path: Path
    initiative_id: int
    raw_text: str

    # ---- factory / persistence -------------------------------------------------

    @classmethod
    def plan_path(cls, repo_path: Path, initiative_id: int) -> Path:
        return Path(repo_path) / ".equipa" / f"initiative-{initiative_id}.md"

    @classmethod
    def _lock_path(cls, plan_path: Path) -> Path:
        return plan_path.with_suffix(plan_path.suffix + ".lock")

    @classmethod
    def load(cls, repo_path: Path, initiative_id: int) -> "InitiativePlan":
        """Read ``.equipa/initiative-<id>.md`` and return a parsed plan.

        Raises ``FileNotFoundError`` if the plan file does not exist —
        callers should usually call :meth:`ensure_exists` first.
        """
        path = cls.plan_path(repo_path, initiative_id)
        if not path.exists():
            raise FileNotFoundError(f"Initiative plan not found: {path}")
        return cls(path=path, initiative_id=initiative_id, raw_text=path.read_text())

    @classmethod
    def ensure_exists(
        cls,
        repo_path: Path,
        initiative_id: int,
        conn: sqlite3.Connection,
    ) -> Path:
        """Create the plan file from the DB row if it does not yet exist.

        Returns the path either way. The DB connection is used read-only.
        """
        path = cls.plan_path(repo_path, initiative_id)
        if path.exists():
            return path

        row = _fetch_initiative_row(conn, initiative_id)
        if row is None:
            raise ValueError(
                f"Cannot create plan: no initiative row for id={initiative_id}"
            )

        content = _render_initial_template(row)
        path.parent.mkdir(parents=True, exist_ok=True)
        _atomic_write(path, content)
        logger.info("Created initiative plan at %s", path)
        return path

    # ---- read -----------------------------------------------------------------

    def to_prompt_context(self) -> str:
        """Return the plan content prefixed with the agent instruction header."""
        return f"{PROMPT_HEADER}\n\n{self.raw_text}"

    # ---- append ---------------------------------------------------------------

    def append_subtask(
        self,
        task_id: int,
        title: str,
        status: str,
        branch: str,
        completed_at: str | datetime | None,
        summary: str,
        decisions: Iterable[tuple[str, str]],
    ) -> None:
        """Append a sub-task entry between the BEGIN/END markers.

        Atomic: write to a temp file in the same directory, then
        ``os.rename`` over the target. A POSIX file lock serialises
        concurrent appends from sibling task dispatches.
        """
        entry = _render_subtask_entry(
            task_id=task_id,
            title=title,
            status=status,
            branch=branch,
            completed_at=completed_at,
            summary=summary,
            decisions=list(decisions),
        )

        lock_path = self._lock_path(self.path)
        with _acquire_lock(lock_path):
            # Re-read inside the lock so we don't clobber a sibling append.
            current = self.path.read_text() if self.path.exists() else self.raw_text
            updated = _insert_before_end_marker(current, entry)
            _atomic_write(self.path, updated)
            self.raw_text = updated


# ---------------------------------------------------------------------------
# Rendering helpers
# ---------------------------------------------------------------------------

def _fetch_initiative_row(
    conn: sqlite3.Connection,
    initiative_id: int,
) -> InitiativeRow | None:
    row = conn.execute(
        """
        SELECT i.id, i.project_id, i.name, i.goal, i.status, i.created_at,
               p.codename
        FROM initiatives i
        LEFT JOIN projects p ON p.id = i.project_id
        WHERE i.id = ?
        """,
        (initiative_id,),
    ).fetchone()
    if row is None:
        return None
    return InitiativeRow(
        id=row[0],
        project_id=row[1],
        name=row[2],
        goal=row[3],
        status=row[4],
        created_at=row[5] or "",
        project_codename=row[6],
    )


def _render_initial_template(row: InitiativeRow) -> str:
    created_date = (row.created_at or "").split(" ", 1)[0] or _today()
    project_label = row.project_codename or f"project_id={row.project_id}"
    return (
        f"# Initiative: {row.name}\n"
        f"\n"
        f"**ID:** {row.id}\n"
        f"**Goal:** {row.goal}\n"
        f"**Status:** {row.status}\n"
        f"**Created:** {created_date}\n"
        f"**Target project:** {project_label}\n"
        f"\n"
        f"---\n"
        f"\n"
        f"## Original Plan\n"
        f"\n"
        f"<!-- Operator: write the initiative's original plan here. -->\n"
        f"\n"
        f"---\n"
        f"\n"
        f"## Sub-tasks\n"
        f"\n"
        f"{HUMAN_EDIT_HINT}\n"
        f"{BEGIN_MARKER}\n"
        f"\n"
        f"{END_MARKER}\n"
    )


def _render_subtask_entry(
    *,
    task_id: int,
    title: str,
    status: str,
    branch: str,
    completed_at: str | datetime | None,
    summary: str,
    decisions: list[tuple[str, str]],
) -> str:
    if isinstance(completed_at, datetime):
        completed_str = completed_at.strftime("%Y-%m-%d %H:%M")
    elif completed_at:
        completed_str = str(completed_at)
    else:
        completed_str = "—"

    lines = [
        f"### #{task_id}: {title}",
        f"**Status:** {status}",
        f"**Branch:** {branch}",
        f"**Completed:** {completed_str}",
        f"**Summary:** {summary or '—'}",
        "**Decisions:**",
    ]
    if decisions:
        for decision, rationale in decisions:
            decision = decision.strip() or "—"
            rationale = rationale.strip()
            if rationale:
                lines.append(f"- {decision} — {rationale}")
            else:
                lines.append(f"- {decision}")
    else:
        lines.append("- (none recorded)")
    lines.append("")  # trailing blank line for separation
    return "\n".join(lines) + "\n"


def _insert_before_end_marker(current: str, entry: str) -> str:
    """Insert ``entry`` immediately before the END marker.

    If markers are missing (file was hand-edited or corrupted), append
    a fresh orchestrator-managed block at the end so the next append
    still has a valid target — but log loudly. We never silently
    overwrite human-edited content above the BEGIN marker.
    """
    if END_MARKER not in current:
        logger.warning(
            "Plan file missing END marker; appending a fresh managed block."
        )
        suffix = (
            f"\n{HUMAN_EDIT_HINT}\n{BEGIN_MARKER}\n\n{entry}{END_MARKER}\n"
        )
        return current.rstrip() + suffix

    head, _, tail = current.rpartition(END_MARKER)
    return f"{head.rstrip()}\n\n{entry}{END_MARKER}{tail}"


def _atomic_write(path: Path, content: str) -> None:
    """Write ``content`` to ``path`` atomically via tempfile + os.rename."""
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp_name = tempfile.mkstemp(
        prefix=path.name + ".",
        suffix=".tmp",
        dir=str(path.parent),
    )
    try:
        with os.fdopen(fd, "w") as fh:
            fh.write(content)
            fh.flush()
            os.fsync(fh.fileno())
        os.replace(tmp_name, str(path))
    except Exception:
        with contextlib.suppress(FileNotFoundError):
            os.unlink(tmp_name)
        raise


def _today() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%d")


# ---------------------------------------------------------------------------
# Orchestrator-side glue
# ---------------------------------------------------------------------------

AGENT_INSTRUCTION_BLOCK = """\
At the END of your task, before signaling completion, emit a final block in this exact format:

<!-- ORCHESTRATOR_OUTPUT -->
SUMMARY: <one-paragraph summary of what you actually did, what worked, what didn't>
DECISIONS:
- <one-line decision> | <one-line rationale>
- <one-line decision> | <one-line rationale>
<!-- /ORCHESTRATOR_OUTPUT -->

The orchestrator parses this block to update the initiative plan file. If you have no
decisions worth recording (purely mechanical task), output `DECISIONS:` with no items.
"""


def build_initiative_prompt_section(
    repo_path: Path,
    initiative_id: int,
    conn: sqlite3.Connection,
) -> str:
    """Build the ``## INITIATIVE CONTEXT`` block injected into agent prompts.

    Ensures the plan file exists, then returns the markdown-formatted
    section. Returns an empty string if anything goes wrong — initiative
    failures must NEVER block task dispatch.
    """
    try:
        InitiativePlan.ensure_exists(repo_path, initiative_id, conn)
        plan = InitiativePlan.load(repo_path, initiative_id)
    except Exception:
        logger.exception(
            "Failed to ensure/load initiative plan for id=%s; "
            "dispatching without initiative context.",
            initiative_id,
        )
        return ""

    return (
        "## INITIATIVE CONTEXT\n\n"
        f"{plan.to_prompt_context()}\n\n"
        f"{AGENT_INSTRUCTION_BLOCK}"
    )


def record_task_completion(
    repo_path: Path,
    initiative_id: int,
    task_id: int,
    title: str,
    status: str,
    branch: str,
    agent_output: str,
    completed_at: datetime | None = None,
) -> bool:
    """Parse the agent output and append a sub-task entry to the plan file.

    Returns True if the plan was updated, False if a fatal error
    prevented the update. Callers should NOT treat a False return as
    cause to abort the task — initiative tracking is best-effort.
    """
    try:
        path = InitiativePlan.plan_path(repo_path, initiative_id)
        if not path.exists():
            logger.warning(
                "Plan file missing at completion time for initiative=%s; "
                "skipping append.",
                initiative_id,
            )
            return False

        parsed = parse_orchestrator_output(agent_output)
        if parsed is None:
            logger.warning(
                "Agent output had no ORCHESTRATOR_OUTPUT block for task=%s; "
                "appending placeholder.",
                task_id,
            )
            summary = "(no orchestrator output block emitted by agent)"
            decisions: list[tuple[str, str]] = []
        else:
            if parsed.malformed:
                logger.warning(
                    "Agent ORCHESTRATOR_OUTPUT block malformed for task=%s; "
                    "captured best-effort.",
                    task_id,
                )
            summary = parsed.summary or "(empty summary)"
            decisions = parsed.decisions

        plan = InitiativePlan.load(repo_path, initiative_id)
        plan.append_subtask(
            task_id=task_id,
            title=title,
            status=status,
            branch=branch,
            completed_at=completed_at or datetime.now(timezone.utc),
            summary=summary,
            decisions=decisions,
        )
        return True
    except Exception:
        logger.exception(
            "Failed to record task completion to initiative plan "
            "(task=%s, initiative=%s)",
            task_id,
            initiative_id,
        )
        return False
